image: cypress/base:14.16.0

stages:
  - test

local-e2e:
  stage: test

  script:
    - npm ci --prefer-offline
    - npm start &
    - npx cypress run --reporter mochawesome  --reporter-options reportDir=mochawesome-report,overwrite=false,html=false,json=true
  artifacts:
    expire_in: 30 days
    when: always
    paths:
      - mochawesome-report
      - cypress/screenshots