image: cypress/base:10

stages:
  - test
test:
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm start &
    - npx cypress run --browser chrome